ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.hackathon.summer.faf.ApplicationKt.module

database:
  jdbcUrl: dsa
  driverClassName: "org.postgresql.Driver"
  username: dsa
  password: dsa
  maximumPoolSize: 10