ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.hackathon.summer.faf.ApplicationKt.module

database:
  jdbcUrl: "jdbc:postgresql://beach_db:5432/beach"
  driverClassName: "org.postgresql.Driver"
  username: "beach_user"
  password: "beach_pass"
  maximumPoolSize: 10